# The Best Neighborhood in Pittsburgh based on Education

In [3]:
import pandas as pd

enrollment = pd.read_csv("https://data.wprdc.org/dataset/27b6eef7-8825-4cc4-8b48-52c17ac80d37/resource/7b0660d1-c812-496d-ab0a-8560902e9e70/download/neighborhood_school_enrollment.csv")
enrollment.head()

       neighborhood                       school  enrolled_students
0  Allegheny Center                        Other                 50
1  Allegheny Center       PITTSBURGH KING PreK-8                 34
2         Allentown                        Other                 96
3         Allentown  PITTSBURGH GRANDVIEW PreK-5                 76
4         Allentown   PITTSBURGH SOUTH HILLS 6-8                 50

In [11]:
enrollment.groupby("neighborhood").sum()

                     enrolled_students
neighborhood
Allegheny Center                    84
Allentown                          289
Arlington                          186
Arlington Heights                   27
Banksville                         180
...                                ...
West End                            28
West Oakland                        54
Westwood                           269
Wilkinsburg Borough                305
Windgap                            110

[87 rows x 1 columns]

In [5]:
feeder = pd.read_csv("https://data.wprdc.org/dataset/27b6eef7-8825-4cc4-8b48-52c17ac80d37/resource/643511e3-e99a-4e2a-94a4-033ddb944e94/download/feeder_enrollment.csv")
feeder.head()

,school,attending_feeder,attending_nonfeeder,total_with_feeder_status,grade_level
0,PITTSBURGH ALLDERDICE HIGH SCHOOL,1064,344,1408,9-12
1,PITTSBURGH ARLINGTON PreK-8,114,190,304,6-8
2,PITTSBURGH ARLINGTON PreK-8,229,285,514,K-5
3,PITTSBURGH ARSENAL 6-8,102,144,246,6-8
4,PITTSBURGH ARSENAL PreK-5,110,155,265,K-5

In [7]:
feeder.groupby("school").sum()

,attending_feeder,attending_nonfeeder,total_with_feeder_status
school,,,
PITTSBURGH ALLDERDICE HIGH SCHOOL,1064,344,1408
PITTSBURGH ARLINGTON PreK-8,343,475,818
PITTSBURGH ARSENAL 6-8,102,144,246
PITTSBURGH ARSENAL PreK-5,110,155,265
PITTSBURGH BANKSVILLE K-5,112,46,158
PITTSBURGH BEECHWOOD PreK-5,210,61,271
PITTSBURGH BRASHEAR HIGH SCHOOL,876,365,1241
PITTSBURGH BROOKLINE PreK-8,383,160,543
PITTSBURGH CARRICK HIGH SCHOOL,654,504,1158
PITTSBURGH COLFAX K-8,792,164,956
PITTSBURGH CONCORD K-5,284,87,371
PITTSBURGH FAISON K-5,449,268,717
PITTSBURGH FULTON PreK-5,119,152,271
PITTSBURGH GRANDVIEW PreK-5,196,173,369
PITTSBURGH GREENFIELD PreK-8,279,62,341
PITTSBURGH KING PreK-8,342,611,953
PITTSBURGH LANGLEY K-8,479,436,915
PITTSBURGH LINCOLN PreK-5,173,214,387
PITTSBURGH MANCHESTER PreK-8,100,108,208
PITTSBURGH MIFFLIN PreK-8,241,106,347
PITTSBURGH MILLER PreK-5,197,152,349
PITTSBURGH MILLIONES 6-12,319,788,1107
PITTSBURGH MINADEO PreK-5,216,201,417
PITTSBURGH MORROW PreK-8,528,490,1018
PITTSBURGH PERRY HIGH SCHOOL,341,571,912
PITTSBURGH PHILLIPS K-5,53,21,74
PITTSBURGH ROOSEVELT PreK-5,213,112,325
PITTSBURGH SCHILLER 6-8,70,28,98
PITTSBURGH SOUTH BROOK 6-8,313,199,512
PITTSBURGH SOUTH HILLS 6-8,370,375,745
PITTSBURGH SPRING HILL K-5,112,85,197
PITTSBURGH STERRETT 6-8,101,121,222
PITTSBURGH SUNNYSIDE PreK-8,215,295,510
PITTSBURGH WEIL PreK-5,134,183,317
PITTSBURGH WEST LIBERTY PreK-5,135,108,243
PITTSBURGH WESTINGHOUSE ACADEMY 6-12,463,866,1329
PITTSBURGH WESTWOOD K-5,168,167,335
PITTSBURGH WHITTIER K-5,159,56,215
PITTSBURGH WOOLSLAIR PreK-5,83,126,209
Wilkinsburg SD,228,69,297

(Look into what is known about the neighborhoods)